services:
  headscale:
    container_name: headscale
    image: headscale/headscale:latest
    restart: unless-stopped
    # ports:
      # - 8080:8080
    volumes:
      - ./config:/etc/headscale
      - ./container-data:/var/lib/headscale
    entrypoint: headscale serve
    networks:
      reverseproxy-nw:

  headscale-ui:
    container_name: headscale-ui
    image: ghcr.io/gurucomputing/headscale-ui:latest
    restart: unless-stopped
    networks:
      reverseproxy-nw:


networks:
  reverseproxy-nw:
    external: true